import { StyleSheet } from "react-native";

const P = "#1D4ED8";

export const invitadoStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F4F6FB" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  headerMarca: { fontSize: 13, fontWeight: "800", color: P, marginBottom: 2 },
  headerTitulo: { fontSize: 22, fontWeight: "800", color: "#111827" },
  headerSub: { fontSize: 12, color: "#6B7280", marginTop: 2 },
  loginBtn: {
    backgroundColor: P,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  loginBtnText: { fontSize: 13, fontWeight: "700", color: "#FFFFFF" },
  bannerIncentivo: {
    backgroundColor: "#1D4ED8",
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  bannerIncentivoText: { fontSize: 13, fontWeight: "600", color: "#FFFFFF" },
  searchWrap: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: "#FFFFFF",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  searchInput: { flex: 1, fontSize: 14, color: "#111827", padding: 0 },
  catsRow: { maxHeight: 50, backgroundColor: "#FFFFFF" },
  catsContent: { paddingHorizontal: 20, paddingBottom: 10, gap: 8 },
  catChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  catChipActive: { backgroundColor: P, borderColor: P },
  catChipText: { fontSize: 13, fontWeight: "600", color: "#6B7280" },
  catChipTextActive: { color: "#FFFFFF" },
  quickFilters: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 8,
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  qfChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  qfChipActive: { backgroundColor: "#EEF2FF", borderColor: P },
  qfText: { fontSize: 12, fontWeight: "600", color: "#6B7280" },
  qfTextActive: { color: P },
  resetChip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
    backgroundColor: "#FEE2E2",
    borderWidth: 1,
    borderColor: "#FECACA",
  },
  resetText: { fontSize: 12, fontWeight: "600", color: "#DC2626" },
  listContent: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 32 },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  cardImg: {
    height: 130,
    width: "100%",
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  cardEmoji: { width: "100%", height: "100%" },
  estadoBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  estadoDot: { width: 6, height: 6, borderRadius: 3 },
  estadoText: { fontSize: 11, fontWeight: "700" },
  invitadoBadge: {
    position: "absolute",
    bottom: 8,
    left: 10,
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  invitadoBadgeText: { fontSize: 10, color: "#FFFFFF", fontWeight: "600" },
  cardBody: { padding: 14 },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  catBadge: {
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  catText: { fontSize: 11, fontWeight: "700", color: P },
  anioText: { fontSize: 12, color: "#9CA3AF" },
  cardNombre: {
    fontSize: 17,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 10,
  },
  specRow: { flexDirection: "row", gap: 8, marginBottom: 12 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F4F6FB",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  pillEmoji: { fontSize: 12 },
  pillText: { fontSize: 11, color: "#6B7280", fontWeight: "500" },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 8,
  },
  precio: { fontSize: 20, fontWeight: "800", color: P },
  precioDia: { fontSize: 11, color: "#9CA3AF" },
  ratingRow: { flexDirection: "row", alignItems: "center", gap: 2 },
  ratingVal: { fontSize: 13, fontWeight: "700", color: "#111827" },
  ratingCount: { fontSize: 11, color: "#9CA3AF" },
  cardSucursal: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  sucursalText: { fontSize: 12, color: "#9CA3AF" },
  kmText: { fontSize: 12, color: "#9CA3AF" },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 21,
    marginBottom: 24,
  },
  emptyBtn: {
    backgroundColor: P,
    borderRadius: 12,
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  emptyBtnText: { fontSize: 14, fontWeight: "700", color: "#FFFFFF" },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "95%",
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: "#E5E7EB",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 4,
  },
  detailHero: {
    height: 280,
    width: "100%",
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  detailEmoji: { width: "100%", height: "100%" },
  detailEstado: {
    position: "absolute",
    bottom: 12,
    right: 16,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
  },
  detailEstadoText: { fontSize: 12, fontWeight: "700" },
  detailHeader: { padding: 20, paddingBottom: 8 },
  detailNombre: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 2,
    marginTop: 8,
  },
  detailAnio: { fontSize: 14, color: "#9CA3AF", marginBottom: 10 },
  starsRow: { flexDirection: "row", alignItems: "center", gap: 3 },
  priceCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 20,
    marginVertical: 12,
    backgroundColor: "#EFF6FF",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "#DBEAFE",
  },
  priceLbl: { fontSize: 12, color: "#6B7280", marginBottom: 2 },
  priceVal: { fontSize: 26, fontWeight: "800", color: P },
  priceSub: { fontSize: 11, color: "#9CA3AF", marginTop: 2 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#111827",
    paddingHorizontal: 20,
    marginBottom: 10,
    marginTop: 4,
  },
  descCard: {
    marginHorizontal: 20,
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 16,
  },
  descText: { fontSize: 14, color: "#374151", lineHeight: 21 },
  specsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 16,
  },
  specCard: {
    width: "47%",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  specIcon: { fontSize: 20, marginBottom: 4 },
  specLbl: { fontSize: 11, color: "#9CA3AF", marginBottom: 2 },
  specVal: { fontSize: 13, fontWeight: "700", color: "#111827" },
  serviciosCard: {
    marginHorizontal: 20,
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    gap: 8,
    marginBottom: 16,
  },
  servicioRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  servicioCheck: { fontSize: 14, color: "#16A34A", fontWeight: "800" },
  servicioText: { fontSize: 13, color: "#374151" },
  calendarioCard: {
    marginHorizontal: 20,
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 16,
  },
  calendarioHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  calendarioMes: { fontSize: 14, fontWeight: "700", color: "#111827" },
  calendarioBadge: {
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  calendarioBadgeText: { fontSize: 10, fontWeight: "600", color: "#D97706" },
  diasRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 6,
  },
  diaLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#9CA3AF",
    width: 30,
    textAlign: "center",
  },
  diasGrid: { flexDirection: "row", flexWrap: "wrap" },
  diaCell: {
    width: "14.28%",
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 6,
    marginVertical: 1,
  },
  diaCellReservado: { backgroundColor: "#FEE2E2" },
  diaCellHoy: { backgroundColor: P },
  diaCellText: { fontSize: 12, color: "#374151" },
  diaCellTextReservado: { color: "#DC2626", fontWeight: "600" },
  diaCellTextHoy: { color: "#FFFFFF", fontWeight: "800" },
  calendarioLeyenda: {
    flexDirection: "row",
    gap: 16,
    marginTop: 10,
    justifyContent: "center",
  },
  leyendaItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  leyendaDot: { width: 12, height: 12, borderRadius: 3 },
  leyendaText: { fontSize: 11, color: "#6B7280" },
  incentivoCard: {
    marginHorizontal: 20,
    backgroundColor: "#EFF6FF",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#DBEAFE",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
  },
  incentivoEmoji: { fontSize: 28 },
  incentivoTextos: { flex: 1 },
  incentivoTitulo: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 2,
  },
  incentivoDesc: { fontSize: 12, color: "#6B7280", lineHeight: 17 },
  actions: {
    flexDirection: "row",
    gap: 10,
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  closeBtn: {
    flex: 0.38,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
  },
  closeBtnText: { fontSize: 14, fontWeight: "600", color: "#6B7280" },
  reservarBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: P,
    alignItems: "center",
  },
  reservarBtnText: { fontSize: 14, fontWeight: "700", color: "#FFFFFF" },
});
