export const COLOR_MARCA = "#2f4ea2";
export const COLOR_ACCENT = "#2563eb";

export const COLORES = {
  pageBg: "#f8fafc",
  panelBg: "#ffffff",
  panelBorder: "#f1f5f9",
  panelBorderStrong: "#e2e8f0",
  panelShadow: "0 2px 12px rgba(0,0,0,0.05)",
  textPrimary: "#0f172a",
  textSecondary: "#64748b",
  textMuted: "#94a3b8",
  textSoft: "#94a3b8",
  accentText: COLOR_MARCA,
  accentGradient: `${COLOR_MARCA}`,
  accentBgSoft: "rgba(30,58,138,0.08)",
  accentBorder: "#bfdbfe",
  inputBg: "#fff",
  inputText: "#334155",
  inputBorder: "#e2e8f0",
  dangerBg: "#fef2f2",
  dangerBorder: "#fecaca",
  dangerText: "#dc2626",
  chipBg: "#f1f5f9",
  chipText: "#475569",
  chipActiveBg: COLOR_MARCA,
  chipActiveText: "#fff",
  cardBorder: "#f1f5f9",
  cardBorderHover: "#bfdbfe",
  cardShadow: "0 2px 8px rgba(0,0,0,0.05)",
  imageFallbackBg: "#f1f5f9",
  imageFallbackIcon: "#94a3b8",
  paginationIdleBg: "#f1f5f9",
  paginationIdleText: "#475569",
  paginationDisabledBg: "#f1f5f9",
  paginationDisabledText: "#94a3b8",
  heroBg: "#eff6ff",
};

export const CATEGORIAS = ["Todos", "Sedan", "SUV", "Económico", "Deportivo"];
export const TRANSMISIONES = ["Todas", "Automática", "Manual"];
export const COMBUSTIBLES = [
  "Todos",
  "Gasolina",
  "Diesel",
  "Híbrido",
  "Eléctrico",
];
export const SUCURSALES = [
  "Todas las sucursales",
  "Localiza (El Dorado)",
  "Tu Roll (El Poblado)",
  "Europcar (El Dorado)",
  "Enterprise (El Dorado)",
  "Sixt (JMC)",
  "Alamo (El Dorado)",
];

export const FILTROS_BASE = {
  categoria: "Todos",
  precioMin: "",
  precioMax: "",
  transmision: "Todas",
  combustible: "Todos",
  sucursal: "Todas las sucursales",
  orden: "precio_asc",
  busqueda: "",
};

export const VEHICULOS_MOCK: import("../types/catalogo.types").Vehiculo[] = [
  {
    id: 1,
    nombre: "Toyota Corolla 2024",
    marca: "Toyota",
    modelo: "Corolla",
    categoria: "Sedan",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 85000,
    calificacion: 4.8,
    disponible: true,
    destacado: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 470,
    cilindraje: "1.8L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: false,
    sucursal: "Localiza (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 85000 },
      kmIlimitado: { precio: 105000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=600&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&q=80",
    ],
  },
  {
    id: 2,
    nombre: "Mazda CX-5 2024",
    marca: "Mazda",
    modelo: "CX-5",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 145000,
    calificacion: 4.9,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 505,
    cilindraje: "2.5L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Tu Roll (El Poblado)",
    tarifas: {
      kmLimitado: { km: 250, precio: 145000 },
      kmIlimitado: { precio: 175000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?w=600&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=80",
    ],
  },
  {
    id: 3,
    nombre: "Chevrolet Spark 2023",
    marca: "Chevrolet",
    modelo: "Spark",
    categoria: "Económico",
    transmision: "Manual",
    combustible: "Gasolina",
    precio: 60000,
    calificacion: 4.5,
    disponible: true,
    puertas: 4,
    pasajeros: 4,
    maletero: 170,
    cilindraje: "1.0L",
    aireAcondicionado: true,
    vidriosElectricos: false,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: false,
    sensoresParqueo: false,
    sucursal: "Europcar (El Dorado)",
    tarifas: {
      kmLimitado: { km: 150, precio: 60000 },
      kmIlimitado: { precio: 75000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=600&q=80",
      "https://images.unsplash.com/photo-1541443131876-44b03de101c5?w=600&q=80",
    ],
  },
  {
    id: 4,
    nombre: "Renault Sandero 2023",
    marca: "Renault",
    modelo: "Sandero",
    categoria: "Económico",
    transmision: "Manual",
    combustible: "Gasolina",
    precio: 55000,
    calificacion: 4.3,
    disponible: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 320,
    cilindraje: "1.6L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: false,
    camaraReversa: false,
    sensoresParqueo: false,
    sucursal: "Alamo (El Dorado)",
    tarifas: {
      kmLimitado: { km: 150, precio: 55000 },
      kmIlimitado: { precio: 68000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600&q=80",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80",
    ],
  },
  {
    id: 5,
    nombre: "Ford Mustang 2024",
    marca: "Ford",
    modelo: "Mustang",
    categoria: "Deportivo",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 250000,
    calificacion: 4.7,
    disponible: false,
    puertas: 2,
    pasajeros: 4,
    maletero: 408,
    cilindraje: "5.0L V8",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Sixt (JMC)",
    tarifas: {
      kmLimitado: { km: 300, precio: 250000 },
      kmIlimitado: { precio: 300000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1611245329358-c8d35210996a?w=600&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600&q=80",
    ],
  },
  {
    id: 6,
    nombre: "Kia Sportage 2024",
    marca: "Kia",
    modelo: "Sportage",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Híbrido",
    precio: 180000,
    calificacion: 4.6,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 543,
    cilindraje: "1.6T Híbrido",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Enterprise (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 180000 },
      kmIlimitado: { precio: 210000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1632245889029-e406faaa34cd?w=600&q=80",
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80",
    ],
  },
  {
    id: 7,
    nombre: "Hyundai Tucson 2024",
    marca: "Hyundai",
    modelo: "Tucson",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 160000,
    calificacion: 4.7,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 513,
    cilindraje: "2.0L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Localiza (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 160000 },
      kmIlimitado: { precio: 190000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1633113215188-4e5b7b9e7e3a?w=600&q=80",
      "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&q=80",
    ],
  },
  {
    id: 8,
    nombre: "Nissan Sentra 2024",
    marca: "Nissan",
    modelo: "Sentra",
    categoria: "Sedan",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 95000,
    calificacion: 4.4,
    disponible: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 502,
    cilindraje: "2.0L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: false,
    sucursal: "Europcar (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 95000 },
      kmIlimitado: { precio: 115000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=600&q=80",
      "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=600&q=80",
    ],
  },
  {
    id: 9,
    nombre: "Volkswagen Golf 2024",
    marca: "Volkswagen",
    modelo: "Golf",
    categoria: "Sedan",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 120000,
    calificacion: 4.6,
    disponible: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 380,
    cilindraje: "1.4T",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Enterprise (El Dorado)",
    tarifas: {
      kmLimitado: { km: 250, precio: 120000 },
      kmIlimitado: { precio: 145000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=600&q=80",
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=80",
    ],
  },
  {
    id: 10,
    nombre: "Honda CR-V 2024",
    marca: "Honda",
    modelo: "CR-V",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Híbrido",
    precio: 195000,
    calificacion: 4.8,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 589,
    cilindraje: "2.0L Híbrido",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Tu Roll (El Poblado)",
    tarifas: {
      kmLimitado: { km: 250, precio: 195000 },
      kmIlimitado: { precio: 225000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80",
      "https://images.unsplash.com/photo-1615887023516-9b6bcd559e87?w=600&q=80",
    ],
  },
  {
    id: 11,
    nombre: "BMW Serie 3 2024",
    marca: "BMW",
    modelo: "Serie 3",
    categoria: "Sedan",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 320000,
    calificacion: 4.9,
    disponible: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 480,
    cilindraje: "2.0T",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Sixt (JMC)",
    tarifas: {
      kmLimitado: { km: 300, precio: 320000 },
      kmIlimitado: { precio: 370000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600&q=80",
      "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=600&q=80",
    ],
  },
  {
    id: 12,
    nombre: "Renault Duster 2024",
    marca: "Renault",
    modelo: "Duster",
    categoria: "SUV",
    transmision: "Manual",
    combustible: "Gasolina",
    precio: 110000,
    calificacion: 4.3,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 445,
    cilindraje: "1.6L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: false,
    camaraReversa: false,
    sensoresParqueo: false,
    sucursal: "Alamo (El Dorado)",
    tarifas: {
      kmLimitado: { km: 150, precio: 110000 },
      kmIlimitado: { precio: 130000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=600&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600&q=80",
    ],
  },
];