// modules/catalogo/constants/catalogo.constants.ts

export const COLOR_MARCA = "#2f4ea2";
export const COLOR_ACCENT = "#2563eb";

export const COLORES = {
  pageBg: "#f8fafc",
  panelBg: "#ffffff",
  panelBorder: "#f1f5f9",
  panelBorderStrong: "#e2e8f0",
  panelShadow: "0 2px 12px rgba(0,0,0,0.05)",
  textPrimary: "#0f172a",
  textSecondary: "#64748b",
  textMuted: "#94a3b8",
  textSoft: "#94a3b8",
  accentText: COLOR_MARCA,
  accentGradient: `${COLOR_MARCA}`,
  accentBgSoft: "rgba(30,58,138,0.08)",
  accentBorder: "#bfdbfe",
  inputBg: "#fff",
  inputText: "#334155",
  inputBorder: "#e2e8f0",
  dangerBg: "#fef2f2",
  dangerBorder: "#fecaca",
  dangerText: "#dc2626",
  chipBg: "#f1f5f9",
  chipText: "#475569",
  chipActiveBg: COLOR_MARCA,
  chipActiveText: "#fff",
  cardBorder: "#f1f5f9",
  cardBorderHover: "#bfdbfe",
  cardShadow: "0 2px 8px rgba(0,0,0,0.05)",
  imageFallbackBg: "#f1f5f9",
  imageFallbackIcon: "#94a3b8",
  paginationIdleBg: "#f1f5f9",
  paginationIdleText: "#475569",
  paginationDisabledBg: "#f1f5f9",
  paginationDisabledText: "#94a3b8",
  heroBg: "#eff6ff",
};

export const CATEGORIAS = ["Todos", "Sedan", "SUV", "Económico", "Deportivo"];
export const TRANSMISIONES = ["Todas", "Automática", "Manual"];
export const COMBUSTIBLES = [
  "Todos",
  "Gasolina",
  "Diesel",
  "Híbrido",
  "Eléctrico",
];
export const SUCURSALES = [
  "Todas las sucursales",
  "Localiza (El Dorado)",
  "Tu Roll (El Poblado)",
  "Europcar (El Dorado)",
  "Enterprise (El Dorado)",
  "Sixt (JMC)",
  "Alamo (El Dorado)",
];

export const FILTROS_BASE = {
  categoria: "Todos",
  precioMin: "",
  precioMax: "",
  transmision: "Todas",
  combustible: "Todos",
  sucursal: "Todas las sucursales",
  orden: "precio_asc",
  busqueda: "",
};

export const VEHICULOS_MOCK: import("../types/catalogo.types").Vehiculo[] = [
  {
    id: 1,
    nombre: "Toyota Corolla 2024",
    categoria: "Sedan",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 85000,
    calificacion: 4.8,
    disponible: true,
    destacado: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 470,
    cilindraje: "1.8L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: false,
    sucursal: "Localiza (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 85000 },
      kmIlimitado: { precio: 105000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/a2cb0b378c25efdb1e116246f84149744c2f4081.jpg",
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/1c6e90229d22ae38444b4c27a5ecedbc3aaa7739.jpg",
    ],
  },
  {
    id: 2,
    nombre: "Mazda CX-5 2024",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 145000,
    calificacion: 4.9,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 505,
    cilindraje: "2.5L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Tu Roll (El Poblado)",
    tarifas: {
      kmLimitado: { km: 250, precio: 145000 },
      kmIlimitado: { precio: 175000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/5acb88622cc00284455f7d6c6e19fd2f5b11a6cd.jpg",
    ],
  },
  {
    id: 3,
    nombre: "Chevrolet Spark 2023",
    categoria: "Económico",
    transmision: "Manual",
    combustible: "Gasolina",
    precio: 60000,
    calificacion: 4.5,
    disponible: true,
    puertas: 4,
    pasajeros: 4,
    maletero: 170,
    cilindraje: "1.0L",
    aireAcondicionado: true,
    vidriosElectricos: false,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: false,
    sensoresParqueo: false,
    sucursal: "Europcar (El Dorado)",
    tarifas: {
      kmLimitado: { km: 150, precio: 60000 },
      kmIlimitado: { precio: 75000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/1c6e90229d22ae38444b4c27a5ecedbc3aaa7739.jpg",
    ],
  },
  {
    id: 4,
    nombre: "Renault Sandero 2023",
    categoria: "Económico",
    transmision: "Manual",
    combustible: "Gasolina",
    precio: 55000,
    calificacion: 4.3,
    disponible: true,
    puertas: 4,
    pasajeros: 5,
    maletero: 320,
    cilindraje: "1.6L",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: false,
    camaraReversa: false,
    sensoresParqueo: false,
    sucursal: "Alamo (El Dorado)",
    tarifas: {
      kmLimitado: { km: 150, precio: 55000 },
      kmIlimitado: { precio: 68000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/5c55d73935760e36ac2c84a6f676e75136c75d1f.jpg",
    ],
  },
  {
    id: 5,
    nombre: "Ford Mustang 2024",
    categoria: "Deportivo",
    transmision: "Automática",
    combustible: "Gasolina",
    precio: 250000,
    calificacion: 4.7,
    disponible: false,
    puertas: 2,
    pasajeros: 4,
    maletero: 408,
    cilindraje: "5.0L V8",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Sixt (JMC)",
    tarifas: {
      kmLimitado: { km: 300, precio: 250000 },
      kmIlimitado: { precio: 300000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/ec7412fd3f8148ee85aeb9d7c9a05577be7409d6.jpg",
    ],
  },
  {
    id: 6,
    nombre: "Kia Sportage 2024",
    categoria: "SUV",
    transmision: "Automática",
    combustible: "Híbrido",
    precio: 180000,
    calificacion: 4.6,
    disponible: true,
    puertas: 5,
    pasajeros: 5,
    maletero: 543,
    cilindraje: "1.6T Híbrido",
    aireAcondicionado: true,
    vidriosElectricos: true,
    cierreCentralizado: true,
    bluetooth: true,
    camaraReversa: true,
    sensoresParqueo: true,
    sucursal: "Enterprise (El Dorado)",
    tarifas: {
      kmLimitado: { km: 200, precio: 180000 },
      kmIlimitado: { precio: 210000 },
    },
    seguros: [
      { nombre: "Protección Obligatoria", precio: 29000 },
      { nombre: "Protección Total", precio: 67000 },
    ],
    imagenes: [
      "https://pplx-res.cloudinary.com/image/upload/pplx_search_images/3660959c1dc9ad6069d89d42723db9cda29afeba.jpg",
    ],
  },
];
